<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository {

    public function getProduitsByCategorie(\AppBundle\Entity\Categorie $cat) {
        $qb = $this->createQueryBuilder('p');

        $qb->leftJoin('p.image', 'i')
                ->addSelect('i')
                ->leftJoin('p.notes', 'n')
                ->addSelect('n')
                ->leftJoin('p.categorie', 'c')
                ->addSelect('c')
                ->where('p.categorie = ?1')
                ->setParameter(1, $cat)
                ->orderBy('p.date', 'DESC');

        $query = $qb->getQuery();

        return $query->getArrayResult();
    }

    public function getProduitByIdWithJoin($id) {
        $qb = $this->createQueryBuilder('p');
        $qb->leftJoin('p.image', 'i')
                ->addSelect('i')
                ->leftJoin('p.categorie', 'c')
                ->addSelect('c')
                ->leftJoin('p.notes', 'n')
                ->addSelect('n')
                ->where('p.id = ?1')
                ->setParameter(1, $id);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }

}
